"""edit servers

Revision ID: 24625e1a3dc2
Revises: 9fa5c17ff15d
Create Date: 2026-01-28 14:59:30.638895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24625e1a3dc2'
down_revision: Union[str, Sequence[str], None] = '9fa5c17ff15d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('hashed_password', sa.String(), nullable=True))
    op.add_column('servers', sa.Column('preshared_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'preshared_key')
    op.drop_column('servers', 'hashed_password')
    # ### end Alembic commands ###
