"""some fix

Revision ID: 5aaf05419b2f
Revises: a0f2bc79a478
Create Date: 2026-01-11 23:24:57.768105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5aaf05419b2f'
down_revision: Union[str, Sequence[str], None] = 'a0f2bc79a478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('user_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('refresh_tokens_user_fkey'), 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'])
    op.drop_column('refresh_tokens', 'user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('user', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('refresh_tokens_user_fkey'), 'refresh_tokens', 'users', ['user'], ['id'])
    op.drop_column('refresh_tokens', 'user_id')
    # ### end Alembic commands ###
