"""edit uservip

Revision ID: f2a5d9dfe7f2
Revises: 078a9ff99a73
Create Date: 2026-01-06 00:43:05.411655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2a5d9dfe7f2'
down_revision: Union[str, Sequence[str], None] = '078a9ff99a73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_vip', 'mac_address1',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users_vip', 'mac_address2',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users_vip', 'mac_address3',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_vip', 'mac_address3',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users_vip', 'mac_address2',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users_vip', 'mac_address1',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
