"""edit servers

Revision ID: fd0b7dba831f
Revises: 24625e1a3dc2
Create Date: 2026-01-28 15:41:32.374200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd0b7dba831f'
down_revision: Union[str, Sequence[str], None] = '24625e1a3dc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('port_api', sa.String(), nullable=True))
    op.drop_column('servers', 'preshared_key')
    op.drop_column('servers', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('servers', sa.Column('preshared_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('servers', 'port_api')
    # ### end Alembic commands ###
